private-proteingym-dms/MTH3_HAEAE_RockahShmuel_2015-fold_contiguous_0:
  answers.csv: 686b8c2bc383c61567553dee09914d72
private-proteingym-dms/MTH3_HAEAE_RockahShmuel_2015-fold_contiguous_1:
  answers.csv: 6740780da38bb3014725518d78443442
private-proteingym-dms/MTH3_HAEAE_RockahShmuel_2015-fold_contiguous_2:
  answers.csv: 4c3f298debdad09e04b826267c57c0db
private-proteingym-dms/MTH3_HAEAE_RockahShmuel_2015-fold_contiguous_3:
  answers.csv: 006a6dc6d9e367026382f7f8b37c72b4
private-proteingym-dms/MTH3_HAEAE_RockahShmuel_2015-fold_contiguous_4:
  answers.csv: bd36c0986bfeec7eec2600793f50f74b
private-proteingym-dms/MTH3_HAEAE_RockahShmuel_2015-fold_modulo_0:
  answers.csv: 25aa739ed44a2afc11ec5f8613802f86
private-proteingym-dms/MTH3_HAEAE_RockahShmuel_2015-fold_modulo_1:
  answers.csv: b510c6ee38b7bae119885f84d77ffef9
private-proteingym-dms/MTH3_HAEAE_RockahShmuel_2015-fold_modulo_2:
  answers.csv: 639acaaeb1092e303b19c59e50af3030
private-proteingym-dms/MTH3_HAEAE_RockahShmuel_2015-fold_modulo_3:
  answers.csv: 6d4274d27ce0c6fd5cd29016ca8f68ec
private-proteingym-dms/MTH3_HAEAE_RockahShmuel_2015-fold_modulo_4:
  answers.csv: ed4afcd0b54fe8bede0692da1baccd74
private-proteingym-dms/MTH3_HAEAE_RockahShmuel_2015-fold_random_0:
  answers.csv: b706bf8098b65e55af5f20e16520583b
private-proteingym-dms/MTH3_HAEAE_RockahShmuel_2015-fold_random_1:
  answers.csv: 7345cf48100005685457978f7b139cad
private-proteingym-dms/MTH3_HAEAE_RockahShmuel_2015-fold_random_2:
  answers.csv: 3ace4adfbc193280ab78a43c41842803
private-proteingym-dms/MTH3_HAEAE_RockahShmuel_2015-fold_random_3:
  answers.csv: cfe23f1ad0e227a42d7bc1b0a8e11fce
private-proteingym-dms/MTH3_HAEAE_RockahShmuel_2015-fold_random_4:
  answers.csv: 612dfff912ced459adcd09af50081e23
public-proteingym-dms/MTH3_HAEAE_RockahShmuel_2015-fold_contiguous_0:
  sample_submission.csv: 54d6c3df1a449129e7e12e7be65517cc
  test_features.csv: eb859851a5e5a683fd4b5a2212fd44a8
  train.csv: 2432f410cbc5793b1cf1927f5dc1370e
public-proteingym-dms/MTH3_HAEAE_RockahShmuel_2015-fold_contiguous_1:
  sample_submission.csv: e66074401a18d74ca9fd702bf502e92c
  test_features.csv: 0b8db1f21febf59fedcf541d5efdd0ca
  train.csv: d7be1cddbb85a7dce057adb3a3a5fd5d
public-proteingym-dms/MTH3_HAEAE_RockahShmuel_2015-fold_contiguous_2:
  sample_submission.csv: 41591aae1e6f7c9a58e5096e3972fa0d
  test_features.csv: 925519f379e7be7ccb203418a24783ea
  train.csv: 9242054c126e4919ebed6e416c9a6e33
public-proteingym-dms/MTH3_HAEAE_RockahShmuel_2015-fold_contiguous_3:
  sample_submission.csv: 15fa2ea56c83628cdae9af13471fd36b
  test_features.csv: 6ad81748657169367ad85ac1126f8804
  train.csv: ae2554bcfc1f290288827401bef66028
public-proteingym-dms/MTH3_HAEAE_RockahShmuel_2015-fold_contiguous_4:
  sample_submission.csv: 7e555d693c5992ab593e92c2506e88dc
  test_features.csv: 17ad0f279814f6dc3aa3815c95993e3e
  train.csv: e2ab198e3f15d9f6c85f0e31f160c6ef
public-proteingym-dms/MTH3_HAEAE_RockahShmuel_2015-fold_modulo_0:
  sample_submission.csv: 8274f5e31dfcfb78e102a905b0535014
  test_features.csv: 28aefdc874b6cc9f117b8e32ec1c1c4d
  train.csv: 0ab94cc158d163339549a96c7e299f48
public-proteingym-dms/MTH3_HAEAE_RockahShmuel_2015-fold_modulo_1:
  sample_submission.csv: 0bd025e6c4ddbb80198ade39d095cc05
  test_features.csv: baa606704150de3d21ba0bb8fa5ee7a3
  train.csv: efad3e29f06b959906a76f4c3df80bbb
public-proteingym-dms/MTH3_HAEAE_RockahShmuel_2015-fold_modulo_2:
  sample_submission.csv: 92cebfd797c48fbb0f3b3a3675c4c64a
  test_features.csv: fbfcafa8d5daac66a301824220bbab3c
  train.csv: ececa7a9f4327d7dcf8bfe56c510116a
public-proteingym-dms/MTH3_HAEAE_RockahShmuel_2015-fold_modulo_3:
  sample_submission.csv: eb2c4abb6cec4635dccec180942b8af2
  test_features.csv: 59d6f2bd19da36b6055f5df2a21982db
  train.csv: 43456f7c56ef5d33839202f1a44ea702
public-proteingym-dms/MTH3_HAEAE_RockahShmuel_2015-fold_modulo_4:
  sample_submission.csv: e66074401a18d74ca9fd702bf502e92c
  test_features.csv: 53b51c55a44c8825b68ccdaee44ffaae
  train.csv: 56b7baf4128a276f4db3e73e26135741
public-proteingym-dms/MTH3_HAEAE_RockahShmuel_2015-fold_random_0:
  sample_submission.csv: 38b6b0078666ba83cd925c93dcff4edc
  test_features.csv: aa98790d333119091b301a594f2b88cf
  train.csv: e54890241e5a30901d240ed5fba892d3
public-proteingym-dms/MTH3_HAEAE_RockahShmuel_2015-fold_random_1:
  sample_submission.csv: b39bf071f1c9e06a17cc236faea4f084
  test_features.csv: 9b5298cac2d7a2dca11b7889cd04bc92
  train.csv: 9eb43f0f3d834acc7ca258e0256d8aee
public-proteingym-dms/MTH3_HAEAE_RockahShmuel_2015-fold_random_2:
  sample_submission.csv: 602b2c62928fc7f4fdbb9a9133931f65
  test_features.csv: fc658d2a90d9a05a137ad60233994800
  train.csv: f551ae2ae4769158b5b5a56bbab329b5
public-proteingym-dms/MTH3_HAEAE_RockahShmuel_2015-fold_random_3:
  sample_submission.csv: b19f0420dfa234accc059e8c698c9299
  test_features.csv: 195caaacecc123737f56712514a9ae03
  train.csv: 54e58635abcfd8b03b106bad69ca4f4a
public-proteingym-dms/MTH3_HAEAE_RockahShmuel_2015-fold_random_4:
  sample_submission.csv: 56d75d1b50a91071e49a54151b512da0
  test_features.csv: 89111f0558424869a087bff0576f7dc4
  train.csv: f94236090a352f25558b0aa497038949
zip: 53b3c9be428aac3724703a877c014f9c
