
id: proteingym-dms/SCIN_STAAR_Tsuboyama_2023_2QFF
name: SCIN_STAAR_Tsuboyama_2023_2QFF
task_type: fitness_prediction
domain: protein_engineering
difficulty: medium
awards_medals: false
prizes: null
description: biomlbench/tasks/proteingym-dms/SCIN_STAAR_Tsuboyama_2023_2QFF/description.md
preparer: biomlbench.tasks.proteingym-dms.SCIN_STAAR_Tsuboyama_2023_2QFF.prepare:prepare

data_source:
  type: proteingym-dms
  benchmark_id: SCIN_STAAR_Tsuboyama_2023_2QFF

dataset:
  answers: proteingym-dms/SCIN_STAAR_Tsuboyama_2023_2QFF/private/answers.csv
  sample_submission: proteingym-dms/SCIN_STAAR_Tsuboyama_2023_2QFF/public/sample_submission.csv

grader:
  name: proteingym-metric
  grade_fn: biomlbench.tasks.proteingym-dms.SCIN_STAAR_Tsuboyama_2023_2QFF.grade:grade

biomedical_metadata:
  modality: protein_sequence
  data_type: single_task
  proteingym_main_metric: spearman

compute_requirements:
  recommended_gpu_memory_gb: 4
  estimated_runtime_minutes: 15
  max_dataset_size_gb: 2
