
id: proteingym-dms/A0A1I9GEU1_NEIME_Kennouche_2019
name: A0A1I9GEU1_NEIME_Kennouche_2019
task_type: fitness_prediction
domain: protein_engineering
difficulty: medium
awards_medals: false
prizes: null
description: biomlbench/tasks/proteingym-dms/A0A1I9GEU1_NEIME_Kennouche_2019/description.md
preparer: biomlbench.tasks.proteingym-dms.A0A1I9GEU1_NEIME_Kennouche_2019.prepare:prepare

data_source:
  type: proteingym-dms
  benchmark_id: A0A1I9GEU1_NEIME_Kennouche_2019

dataset:
  answers: proteingym-dms/A0A1I9GEU1_NEIME_Kennouche_2019/private/answers.csv
  sample_submission: proteingym-dms/A0A1I9GEU1_NEIME_Kennouche_2019/public/sample_submission.csv

grader:
  name: proteingym-metric
  grade_fn: biomlbench.tasks.proteingym-dms.A0A1I9GEU1_NEIME_Kennouche_2019.grade:grade

biomedical_metadata:
  modality: protein_sequence
  data_type: single_task
  proteingym_main_metric: spearman

compute_requirements:
  recommended_gpu_memory_gb: 4
  estimated_runtime_minutes: 15
  max_dataset_size_gb: 2
