
id: proteingym-dms/CAS9_STRP1_Spencer_2017_positive
name: CAS9_STRP1_Spencer_2017_positive
task_type: fitness_prediction
domain: protein_engineering
difficulty: medium
awards_medals: false
prizes: null
description: biomlbench/tasks/proteingym-dms/CAS9_STRP1_Spencer_2017_positive/description.md
preparer: biomlbench.tasks.proteingym-dms.CAS9_STRP1_Spencer_2017_positive.prepare:prepare

data_source:
  type: proteingym-dms
  benchmark_id: CAS9_STRP1_Spencer_2017_positive

dataset:
  answers: proteingym-dms/CAS9_STRP1_Spencer_2017_positive/private/answers.csv
  sample_submission: proteingym-dms/CAS9_STRP1_Spencer_2017_positive/public/sample_submission.csv

grader:
  name: proteingym-metric
  grade_fn: biomlbench.tasks.proteingym-dms.CAS9_STRP1_Spencer_2017_positive.grade:grade

biomedical_metadata:
  modality: protein_sequence
  data_type: single_task
  proteingym_main_metric: spearman

compute_requirements:
  recommended_gpu_memory_gb: 4
  estimated_runtime_minutes: 15
  max_dataset_size_gb: 2
