
id: proteingym-dms/I6TAH8_I68A0_Doud_2015
name: I6TAH8_I68A0_Doud_2015
task_type: fitness_prediction
domain: protein_engineering
difficulty: medium
awards_medals: false
prizes: null
description: biomlbench/tasks/proteingym-dms/I6TAH8_I68A0_Doud_2015/description.md
preparer: biomlbench.tasks.proteingym-dms.I6TAH8_I68A0_Doud_2015.prepare:prepare

data_source:
  type: proteingym-dms
  benchmark_id: I6TAH8_I68A0_Doud_2015

dataset:
  answers: proteingym-dms/I6TAH8_I68A0_Doud_2015/private/answers.csv
  sample_submission: proteingym-dms/I6TAH8_I68A0_Doud_2015/public/sample_submission.csv

grader:
  name: proteingym-metric
  grade_fn: biomlbench.tasks.proteingym-dms.I6TAH8_I68A0_Doud_2015.grade:grade

biomedical_metadata:
  modality: protein_sequence
  data_type: single_task
  proteingym_main_metric: spearman

compute_requirements:
  recommended_gpu_memory_gb: 4
  estimated_runtime_minutes: 15
  max_dataset_size_gb: 2
