
id: proteingym-dms/VRPI_BPT7_Tsuboyama_2023_2WNM
name: VRPI_BPT7_Tsuboyama_2023_2WNM
task_type: fitness_prediction
domain: protein_engineering
difficulty: medium
awards_medals: false
prizes: null
description: biomlbench/tasks/proteingym-dms/VRPI_BPT7_Tsuboyama_2023_2WNM/description.md
preparer: biomlbench.tasks.proteingym-dms.VRPI_BPT7_Tsuboyama_2023_2WNM.prepare:prepare

data_source:
  type: proteingym-dms
  benchmark_id: VRPI_BPT7_Tsuboyama_2023_2WNM

dataset:
  answers: proteingym-dms/VRPI_BPT7_Tsuboyama_2023_2WNM/private/answers.csv
  sample_submission: proteingym-dms/VRPI_BPT7_Tsuboyama_2023_2WNM/public/sample_submission.csv

grader:
  name: proteingym-metric
  grade_fn: biomlbench.tasks.proteingym-dms.VRPI_BPT7_Tsuboyama_2023_2WNM.grade:grade

biomedical_metadata:
  modality: protein_sequence
  data_type: single_task
  proteingym_main_metric: spearman

compute_requirements:
  recommended_gpu_memory_gb: 4
  estimated_runtime_minutes: 15
  max_dataset_size_gb: 2
