private-proteingym-dms/HXK4_HUMAN_Gersing_2022_activity-fold_contiguous_0:
  answers.csv: d6c45d291a5a3fb96f2a24bb519299b2
private-proteingym-dms/HXK4_HUMAN_Gersing_2022_activity-fold_contiguous_1:
  answers.csv: e19e7e0d7ac2b8beb8fa2ed3584e83fd
private-proteingym-dms/HXK4_HUMAN_Gersing_2022_activity-fold_contiguous_2:
  answers.csv: bf08d072e6ad4a6e373cce64e9dfe680
private-proteingym-dms/HXK4_HUMAN_Gersing_2022_activity-fold_contiguous_3:
  answers.csv: e18e7fc34535b3dc3c966cced46c970e
private-proteingym-dms/HXK4_HUMAN_Gersing_2022_activity-fold_contiguous_4:
  answers.csv: 7b2c25ec3d14c016e867a59fa4f60c42
private-proteingym-dms/HXK4_HUMAN_Gersing_2022_activity-fold_modulo_0:
  answers.csv: a818600a606360d42cb273072054b3e4
private-proteingym-dms/HXK4_HUMAN_Gersing_2022_activity-fold_modulo_1:
  answers.csv: e3dc4917c421dd14dae3359919abdf5c
private-proteingym-dms/HXK4_HUMAN_Gersing_2022_activity-fold_modulo_2:
  answers.csv: 45be8a2a60b38834ba8e4fe7d04cef14
private-proteingym-dms/HXK4_HUMAN_Gersing_2022_activity-fold_modulo_3:
  answers.csv: 056cb465f9755a3b74395ae01375bb62
private-proteingym-dms/HXK4_HUMAN_Gersing_2022_activity-fold_modulo_4:
  answers.csv: 75b8a54d763fa472454540099a5483bd
private-proteingym-dms/HXK4_HUMAN_Gersing_2022_activity-fold_random_0:
  answers.csv: f2f311bc479b9d5f061cb15d045bf101
private-proteingym-dms/HXK4_HUMAN_Gersing_2022_activity-fold_random_1:
  answers.csv: 72e8b8882b420524ca56eb15526b5407
private-proteingym-dms/HXK4_HUMAN_Gersing_2022_activity-fold_random_2:
  answers.csv: ea4736410eb3a65651c9778cf663e029
private-proteingym-dms/HXK4_HUMAN_Gersing_2022_activity-fold_random_3:
  answers.csv: ee29df8aea9908f18c8730082dcb1ed9
private-proteingym-dms/HXK4_HUMAN_Gersing_2022_activity-fold_random_4:
  answers.csv: 48266cc26daa4e71a354224ecdd9ff67
public-proteingym-dms/HXK4_HUMAN_Gersing_2022_activity-fold_contiguous_0:
  sample_submission.csv: 1254f55b0b9e3a4b30b53f21eeb659bb
  test_features.csv: b8e85be779eea57bc23b6ca55ceeab3f
  train.csv: 91cc69ecb31e6d93c6e96d3b4fe891d3
public-proteingym-dms/HXK4_HUMAN_Gersing_2022_activity-fold_contiguous_1:
  sample_submission.csv: 8028c35b166738f710848b4aacc3eb98
  test_features.csv: 9d621b65ea9ddbe1a0b5f840a78b9d53
  train.csv: cc4219697efb3194ac485bf37fdb53b0
public-proteingym-dms/HXK4_HUMAN_Gersing_2022_activity-fold_contiguous_2:
  sample_submission.csv: f9b295543cdf004d5c8f090705fd8885
  test_features.csv: 866a0997a8060e701cd1a47cdcb557eb
  train.csv: e2a8d1d1256972acc575e28adb2e161b
public-proteingym-dms/HXK4_HUMAN_Gersing_2022_activity-fold_contiguous_3:
  sample_submission.csv: 0a712e20d77f39f013c7d2d3de4018c1
  test_features.csv: e937af33478cb56b8e10b87fe5ba989a
  train.csv: e6ed11c6081a56084431244f7a460fd8
public-proteingym-dms/HXK4_HUMAN_Gersing_2022_activity-fold_contiguous_4:
  sample_submission.csv: 0ac04d3dbcf9c9e0c75989aa456812b2
  test_features.csv: 2686c0dcec5c2246e92c0d4b805a15eb
  train.csv: bf599d15310181b3e4a8723ab37f745e
public-proteingym-dms/HXK4_HUMAN_Gersing_2022_activity-fold_modulo_0:
  sample_submission.csv: d94c2f933bfe0376d1d175517a1adf2a
  test_features.csv: b1b290e3e4019ba146d910ca6b3835eb
  train.csv: dbd9e1984c17e4c9d374c7f81dd0b7c6
public-proteingym-dms/HXK4_HUMAN_Gersing_2022_activity-fold_modulo_1:
  sample_submission.csv: b3fe907ca028e75e3ae8d005a27941ab
  test_features.csv: 17d0d89005ca57978c7993c6a6ea3906
  train.csv: 8ba77d98aa768f21684533be8657aac8
public-proteingym-dms/HXK4_HUMAN_Gersing_2022_activity-fold_modulo_2:
  sample_submission.csv: 15a8dafca6e8b057ccc1b500c67a4bec
  test_features.csv: 02e3c308289c5365edaadb97a74ce6e0
  train.csv: 197315da6587112499822c365d874367
public-proteingym-dms/HXK4_HUMAN_Gersing_2022_activity-fold_modulo_3:
  sample_submission.csv: 37f07f35b33b7543cd0d7ecc84b59484
  test_features.csv: 721b767b09c6c0464589ca406f730522
  train.csv: 2bd7e177de05583d29dc8a915139ecd7
public-proteingym-dms/HXK4_HUMAN_Gersing_2022_activity-fold_modulo_4:
  sample_submission.csv: 37f07f35b33b7543cd0d7ecc84b59484
  test_features.csv: 7ba875cc8fd6c0a4d16292003828ef40
  train.csv: 143394393d2eb1fc170c7475299c9c7b
public-proteingym-dms/HXK4_HUMAN_Gersing_2022_activity-fold_random_0:
  sample_submission.csv: 2a56c952fb628858ad73b65f2e88a47e
  test_features.csv: 196c0f1444a5ab01dacf32d02cc8a7f4
  train.csv: 7f2a6aa6e8ab5f51f1d33529c8e81f33
public-proteingym-dms/HXK4_HUMAN_Gersing_2022_activity-fold_random_1:
  sample_submission.csv: ac95e2db7eee73fd12d0109de47b23e3
  test_features.csv: 42eb84c6f29363c343d62f89d80e687a
  train.csv: 31de50410b6fa41bdb652b9eb18756fc
public-proteingym-dms/HXK4_HUMAN_Gersing_2022_activity-fold_random_2:
  sample_submission.csv: b41f2c02fca0cb0b51aa7c339369a00b
  test_features.csv: 95f8bdb8df8b03b30b2bde9b0cb623ea
  train.csv: 031e9989a8d27b1566fe1ffae5d97e50
public-proteingym-dms/HXK4_HUMAN_Gersing_2022_activity-fold_random_3:
  sample_submission.csv: ccd9f39685026d2199be53d17dbc4f52
  test_features.csv: a898fc093eb5167c451d9e9f6b4fc937
  train.csv: 5f3a436ca71e378b1aee6520cbf5ce00
public-proteingym-dms/HXK4_HUMAN_Gersing_2022_activity-fold_random_4:
  sample_submission.csv: 5afc6b3ed9445c70ba1d0970b8df5485
  test_features.csv: f100e7de991f342e9bdddeeb50b0b564
  train.csv: 604c8fac1ef220df127803a43197f9b9
zip: 53b3c9be428aac3724703a877c014f9c
