
id: proteingym-dms/SOX30_HUMAN_Tsuboyama_2023_7JJK
name: SOX30_HUMAN_Tsuboyama_2023_7JJK
task_type: fitness_prediction
domain: protein_engineering
difficulty: medium
awards_medals: false
prizes: null
description: biomlbench/tasks/proteingym-dms/SOX30_HUMAN_Tsuboyama_2023_7JJK/description.md
preparer: biomlbench.tasks.proteingym-dms.SOX30_HUMAN_Tsuboyama_2023_7JJK.prepare:prepare

data_source:
  type: proteingym-dms
  benchmark_id: SOX30_HUMAN_Tsuboyama_2023_7JJK

dataset:
  answers: proteingym-dms/SOX30_HUMAN_Tsuboyama_2023_7JJK/private/answers.csv
  sample_submission: proteingym-dms/SOX30_HUMAN_Tsuboyama_2023_7JJK/public/sample_submission.csv

grader:
  name: proteingym-metric
  grade_fn: biomlbench.tasks.proteingym-dms.SOX30_HUMAN_Tsuboyama_2023_7JJK.grade:grade

biomedical_metadata:
  modality: protein_sequence
  data_type: single_task
  proteingym_main_metric: spearman

compute_requirements:
  recommended_gpu_memory_gb: 4
  estimated_runtime_minutes: 15
  max_dataset_size_gb: 2
