
id: proteingym-dms/KCNJ2_MOUSE_Coyote-Maestas_2022_surface
name: KCNJ2_MOUSE_Coyote-Maestas_2022_surface
task_type: fitness_prediction
domain: protein_engineering
difficulty: medium
awards_medals: false
prizes: null
description: biomlbench/tasks/proteingym-dms/KCNJ2_MOUSE_Coyote-Maestas_2022_surface/description.md
preparer: biomlbench.tasks.proteingym-dms.KCNJ2_MOUSE_Coyote-Maestas_2022_surface.prepare:prepare

data_source:
  type: proteingym-dms
  benchmark_id: KCNJ2_MOUSE_Coyote-Maestas_2022_surface

dataset:
  answers: proteingym-dms/KCNJ2_MOUSE_Coyote-Maestas_2022_surface/private/answers.csv
  sample_submission: proteingym-dms/KCNJ2_MOUSE_Coyote-Maestas_2022_surface/public/sample_submission.csv

grader:
  name: proteingym-metric
  grade_fn: biomlbench.tasks.proteingym-dms.KCNJ2_MOUSE_Coyote-Maestas_2022_surface.grade:grade

biomedical_metadata:
  modality: protein_sequence
  data_type: single_task
  proteingym_main_metric: spearman

compute_requirements:
  recommended_gpu_memory_gb: 4
  estimated_runtime_minutes: 15
  max_dataset_size_gb: 2
