private-proteingym-dms/GLPA_HUMAN_Elazar_2016-fold_contiguous_0:
  answers.csv: f9340820ecd91d141c31dec91a088c4b
private-proteingym-dms/GLPA_HUMAN_Elazar_2016-fold_contiguous_1:
  answers.csv: ba1113c698af8bd3f9c2605391853131
private-proteingym-dms/GLPA_HUMAN_Elazar_2016-fold_contiguous_2:
  answers.csv: 078eef00aed4398d4a48f63ebfeb9961
private-proteingym-dms/GLPA_HUMAN_Elazar_2016-fold_contiguous_3:
  answers.csv: 6fcbed7fe192ff8f55dfda6b80175028
private-proteingym-dms/GLPA_HUMAN_Elazar_2016-fold_contiguous_4:
  answers.csv: e5a59a7c53fc5d634cedfd5ec9bdc322
private-proteingym-dms/GLPA_HUMAN_Elazar_2016-fold_modulo_0:
  answers.csv: dcc71a7e9bee1c9db9a880af0bd0867a
private-proteingym-dms/GLPA_HUMAN_Elazar_2016-fold_modulo_1:
  answers.csv: 03dbd463a391416d2517d4b4210457de
private-proteingym-dms/GLPA_HUMAN_Elazar_2016-fold_modulo_2:
  answers.csv: 49c60c21fa557968bfccfc8b7b378ee9
private-proteingym-dms/GLPA_HUMAN_Elazar_2016-fold_modulo_3:
  answers.csv: 661805247d8a0e4bfc0ca5f40d1846f9
private-proteingym-dms/GLPA_HUMAN_Elazar_2016-fold_modulo_4:
  answers.csv: 0c1d4a5f1037a40e26e464b1be4f2e26
private-proteingym-dms/GLPA_HUMAN_Elazar_2016-fold_random_0:
  answers.csv: 39bfcb8e490bd953e75c51204d7b1e2d
private-proteingym-dms/GLPA_HUMAN_Elazar_2016-fold_random_1:
  answers.csv: 3cdbd18e4aaeeb3e92ea7a0412a44d48
private-proteingym-dms/GLPA_HUMAN_Elazar_2016-fold_random_2:
  answers.csv: ae08f0efa6c17def1ea21d711960bead
private-proteingym-dms/GLPA_HUMAN_Elazar_2016-fold_random_3:
  answers.csv: fa6ed5c47dbc9f0e30b33309c3b64818
private-proteingym-dms/GLPA_HUMAN_Elazar_2016-fold_random_4:
  answers.csv: 7ce44641a58ad545a87ce6e97e1a68ce
public-proteingym-dms/GLPA_HUMAN_Elazar_2016-fold_contiguous_0:
  sample_submission.csv: e622d6a29c098b4aefbda5524900df32
  test_features.csv: 3b72b42842cde7bbe5416504c1cea64e
  train.csv: 7506c0549a5ec39d8137e9c77ce44ee8
public-proteingym-dms/GLPA_HUMAN_Elazar_2016-fold_contiguous_1:
  sample_submission.csv: d887c3631930806007256717076eb737
  test_features.csv: 9699e7483a36be86a0a3dbff016bb5dd
  train.csv: 26e8f6599a0d854ebfccddfab7b6868c
public-proteingym-dms/GLPA_HUMAN_Elazar_2016-fold_contiguous_2:
  sample_submission.csv: e783784cd12761411c29ce3c83e6c46b
  test_features.csv: 6de88ff6a548de713f8a8fb9be95d429
  train.csv: 93528004b6efb5ec7cd60eabeafe84ce
public-proteingym-dms/GLPA_HUMAN_Elazar_2016-fold_contiguous_3:
  sample_submission.csv: be1680aa1a855f31bd10268d2086bd5f
  test_features.csv: f1bb261108ce6f5dda0b65d1976b8864
  train.csv: 8d5ee455f8c52908f03b136f5fb01d57
public-proteingym-dms/GLPA_HUMAN_Elazar_2016-fold_contiguous_4:
  sample_submission.csv: 6749758d1d077790ba270f23d2a52a36
  test_features.csv: c9c6597f113738cc7661b7034ca96055
  train.csv: 7de00d941a1b74f80ff0dd98c082769b
public-proteingym-dms/GLPA_HUMAN_Elazar_2016-fold_modulo_0:
  sample_submission.csv: 17f25b53622516ebd10e1fe59f319f15
  test_features.csv: e3bea984b31a0dac4f53bc7314c6919a
  train.csv: 3c2df7f1e7ca8255dab769d66b5ffa0e
public-proteingym-dms/GLPA_HUMAN_Elazar_2016-fold_modulo_1:
  sample_submission.csv: e622d6a29c098b4aefbda5524900df32
  test_features.csv: 7b051b5b836dc49eeb13c6c4490348c0
  train.csv: 6cecd6972996d54e414ad0fc922c7c9f
public-proteingym-dms/GLPA_HUMAN_Elazar_2016-fold_modulo_2:
  sample_submission.csv: 32144810b2a407d59bc3e9f80a4932a0
  test_features.csv: 145bac87601045367f1510cbadaf3e8e
  train.csv: a7da1047e29c0e784d3f708e09144423
public-proteingym-dms/GLPA_HUMAN_Elazar_2016-fold_modulo_3:
  sample_submission.csv: 6749758d1d077790ba270f23d2a52a36
  test_features.csv: aa07169363f42db136d80de0849618f7
  train.csv: 1f1c38b343ce7af6f3ca17179eecb4b4
public-proteingym-dms/GLPA_HUMAN_Elazar_2016-fold_modulo_4:
  sample_submission.csv: 6365c0f7c9815df218f19f3b54eecc29
  test_features.csv: 4b31b832aed3240c923435e48563a589
  train.csv: ff1f4dd02e7c66eae0fb8998a2257a3a
public-proteingym-dms/GLPA_HUMAN_Elazar_2016-fold_random_0:
  sample_submission.csv: 9a9ec031cd6e6abfd4a9c4677508ee02
  test_features.csv: 154268df4a3695414a83cae5e0c438bb
  train.csv: 528c75e7beb67aa781cbd1dce39fa53f
public-proteingym-dms/GLPA_HUMAN_Elazar_2016-fold_random_1:
  sample_submission.csv: c86b5f4d21c9ae1ea14b12dd229775a9
  test_features.csv: d42510ff3b314def0b9284fb3c176edc
  train.csv: d710d930ed873dc2ea97c721c095e876
public-proteingym-dms/GLPA_HUMAN_Elazar_2016-fold_random_2:
  sample_submission.csv: f93371021cf30bbdad55e15c6e2f2d13
  test_features.csv: f851df46dd72ed68c319418a48d808f1
  train.csv: abd7141cd62bbab4fa9812da453d987d
public-proteingym-dms/GLPA_HUMAN_Elazar_2016-fold_random_3:
  sample_submission.csv: 916649fa1eaa9a2134aac5b3c4c14e1a
  test_features.csv: fc6ea5e9fe837104dac38beb8390d9e1
  train.csv: 2e2c73a78a36c83c9e0ad147e8a4d3ec
public-proteingym-dms/GLPA_HUMAN_Elazar_2016-fold_random_4:
  sample_submission.csv: 41563136ec73fa362f7e1eb6d9ace139
  test_features.csv: 760e8dd8edea1b44849bef865e17770b
  train.csv: 4eba747391f71bfd82d50f6676b60db4
zip: 53b3c9be428aac3724703a877c014f9c
